name: SantaFilter Auto Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller audiolab pyrnnoise

      - name: Build EXE
        run: |
          python -m PyInstaller --noconsole --onedir SantaFilter.py

      - name: Zip build
        run: |
          powershell Compress-Archive -Path dist\SantaFilter\* -DestinationPath SantaFilter.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: SantaFilter.zip
        env:
          GITHUB_TOKEN: ${{ secrets.SANTAFILTER_TOKEN }}